### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by dustingetz** [stipsan/String.Slugify.js#2]
Can you add a license please as it seems your intent is to share this code? I can't use this without a license.

**Comment by stipsan** [comment]
You are asking about a LICENSE.md file perhaps?

Since this script is depending on MooTools code I'm using MIT just as they are, as seen here: https://github.com/stipsan/String.Slugify.js/blob/master/Source/String.Slugify.js#L8

**Comment by dustingetz** [comment]
Oops, sorry about that.

**Comment by stipsan** [comment]
@dustingetz no worries! :)
